QRsite/QRer/urls.py
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.contrib import admin

from . import views #resultpage,frontpage,index,ContactFormView

app_name = 'QRer'

urlpatterns = [
    path('result/', views.resultpage, name='result'),
    path('', views.frontpage, name='frontpage'),
    path('main/', views.index, name='index'),
    path('maker/', views.maker, name='maker'),
    path('contact/', views.ContactFormView.as_view(), name='contact'),
    path('contact/result', views.ContactResultView.as_view(), name='contact_result'),
    path('accounts/', include('accounts.urls')),
    path('accounts/logout', views.logout_view),
    path('accounts/', include('django.contrib.auth.urls')),
]

QRsite/QRsite/urls.py
from django.contrib import admin
from django.urls import path,include

from QRer.views import frontpage
from QRer.views import resultpage


urlpatterns = [
    path('', frontpage, name='input'),
    path('result', resultpage, name='result' ),
    path('QRer/', include('QRer.urls')),
    path('admin/', admin.site.urls),

]

QRsite/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    #path('signup/', views.SignUpView.as_view(), name='signup'),
]

QRsite/QRer/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.

class Contact(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    date = models.DateField(auto_now_add=True)
    email = models.EmailField(blank=True, max_length=100)

    def __str__(self):
        return str(self.title)

    class Meta:
        db_table = 'contacts'


class CustomUser(AbstractUser):
    studentname = models.CharField(max_length=100)
    first_name = None
    last_name = None

    # usernameとpasswordの指定は不要
    REQUIRED_FIELDS = ["email", "studentname"]

QRsite/accounts/models.py
from django.db import models

# Create your models here.

QRsite/QRer/forms.py
from django import forms
from .models import Contact

class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ['title', 'email' , 'content']
        labels = {
           'title':'タイトル',
           'email': 'メールアドレス',
           'content':'内容',
        }

QRsite/QRer/views.py
from django.shortcuts import render
from django.views.generic.edit import CreateView
from django.views.generic import TemplateView
from .forms import ContactForm
from django.urls import reverse_lazy
from .models import Contact
from django.contrib.auth.decorators import login_required
import os
from django.shortcuts import redirect
import datetime



class ContactFormView(CreateView):
    template_name = 'QRer/contact.html'
    form_class = ContactForm
    success_url = reverse_lazy('QRer:contact_result')
    model = Contact

class ContactResultView(TemplateView):
    template_name = "QRer/contact_result.html"


# Create your views here.

sigma = {'0':'92','1':'38','2':'47','3':'05','4':'58','5':'09','6':'89','7':'96','8':'30','9':'12'}
def encryption(m):
    c = [sigma[a] for a in m]
    return c
 

#def rend(request):
    #return render(request, "QRer/result.html")    

def frontpage(request):
    return render(request, "QRer/top.html")


def resultpage(request):
    return render(request, "QRer/result.html")


def index2(request):
    return render(request, "QRer/index.html")

def logout_view(request):
    return render(request, "QRer/logged_out.html")


 
def sample(request):
    dt_now = datetime.datetime.now()
    time_left = dt_now + datetime.timedelta(minutes=90)
    strftime_time_left = time_left.time_left_at.strftime('%B %d,%Y %H:%M:%S')
    context = {
    'time_left': strftime_time_left
    }
    return render(request, 'QRer/main.html', context)    



@login_required(login_url='/QRer/accounts/login')
def maker(request):
    if not request.user.is_superuser:
        return redirect('QRer:index')
    p1 = request.POST.get('p1', '')
    alert = {'error':"正しく入力してください"}
    try:
        poke = ''.join(encryption(p1))
    except:
        return render(request, 'QRer/index.html', alert)

    params = {'p2': f"https://chart.apis.google.com/chart?cht=qr&chs=300x300&chl={poke}", 'p3':f"学籍番号：{p1}"}
    alert = {'error':"*学籍番号を数字8桁で正しく入力してください"}
    try:
        if 20220300 > int(p1) > 20170000:
            return render(request, 'QRer/index.html', params)
        else:
            return render(request, 'QRer/index.html', alert)
    except:
        return render(request, 'QRer/index.html')


@login_required(login_url='/QRer/accounts/login')
def index(request):
    username = request.user
    alert = {'error':"生徒用アカウントでログインして下さい"}
    params = {'p2':"", 'p3':""}
    dt_now = datetime.datetime.now()
    time_left = dt_now + datetime.timedelta(minutes=1)
    strftime_time_left = time_left.strftime('%B %d,%Y %H:%M:%S')
    #context = {'time_left': strftime_time_left}

    try:
        poke = ''.join(encryption(str(username)))
    except:
        return render(request, 'QRer/main.html', alert)
    if request.method == "POST":
            if "type_1" in request.POST:
                params = {'url':f"https://chart.apis.google.com/chart?cht=qr&chs=300x300&chl={poke}", 'p3':f"学籍番号：{username}", 'p4':'通常用 /', 'p5':'/static/js/sample.js'}
                print(strftime_time_left)
            elif "type_2"  in request.POST:
                params = {'url':f"https://chart.apis.google.com/chart?cht=qr&chs=300x300&chl={username}", 'p3':f"学籍番号：{username}", 'p4':'例外用 /', 'p5':'/static/js/sample.js'}

    
    return render(request, 'QRer/main.html', params)

QRsite/accounts/views.py
from django.shortcuts import render

# Create your views here.

QRsite/QRer/templates/QRer/contact.html
{% extends "base.html" %}

{% block title %}
こんにちは
{% endblock title %}

{% block content %}
<div class="container mt-3">
    <div class="text-center mb-5">
        <h2 class="mb-5 mt-3">ご意見・ご感想</h2>
<form method="POST" class="mx-3 mx-md-5">
    {% csrf_token %}
	{% for item in form %}
    <div class="form-group mb-3 fs-5">
        <label for="{{item.id_for_label}}">{{item.label}}</label>
        {% if item.name == "content" %}
        <textarea class="form-control" {% if item.field.required %}required{% endif %} name="{{item.name}}" id="{{item.id_for_label}}" rows="3"></textarea>
        {% else %}
        <input type="{{item.field.widget.input_type}}" class="form-control" 
            {% if item.field.required %}required{% endif %} 
            name="{{item.name}}" id="{{item.id_for_label}}">
        {% endif %}
    </div>
    {% endfor %}
    <div class="py-3">
        <button class="btn btn-secondary btn-lg w-100" type="submit">送信</button>
    </div>
</form>
</div>
</div>
{% endblock content %}

QRsite/QRer/templates/QRer/contact_result.html
{% extends "base.html" %}

{% block title %}
こんにちは
{% endblock title %}


{% block content %}
<div class="container mt-3">
    <div class="text-center mb-5">
<h2 class="mb-5">ご意見・ご感想</h2>
<h4>送信が完了しました</h4>
<p>ご協力いただきありがとうございました。</p>

<a href="{% url 'QRer:frontpage'%}">トップ画面へもどる</a>

<script src="/static/js/sample.js"></script>

</div>
</div>

{% endblock content %}

QRsite/QRer/templates/QRer/index.html
{% extends "base.html" %}

{% block title %}
こんにちは
{% endblock title %}

{% block content %}
<h2>専用QRコードを生成 (通常用)</h2>
<p> {{ message }}</p>
<p>学籍番号を半角数字で入力し、生成するボタンを押してください</p>

<form action="" method="post">
    {% csrf_token %}
    
        <div class="row justify-content-center">
    
    <input type="text" class="form-control" name="p1" id="msg" value="{{ p1 }}" style="width: 250px;" placeholder="例：20180300" >
    <input type="submit" class="btn btn-secondary" name="button" id="button" value="生成する">
 
</div>

</form>
<center>
<p><font color="red">{{ error }}</font></p>
<img src="{{ p2 }}" alt="">
<p>{{ p3 }}</p>
</center>



{% endblock content %}

QRsite/QRer/templates/QRer/main.html
{% extends "base.html" %}
{% load static %}

{% block title %}
こんにちは
{% endblock title %}

{% block content %}
<h2>専用QRコードを表示</h2>

<p><font color="red">{{ error }}</font></p>

<center>
{% if not user.is_staff %}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <p><input type="submit" name="type_1" value="通常用" class="btn btn-outline-info btn-lg w-100"></p>
    <p><input type="submit" name="type_2" value="例外用" class="btn btn-outline-info btn-lg w-100"></p>
</form>
{% endif %}


    <img src="{{ url }}" alt="">
    <p>{{ p4 }} {{ p3 }}</p>
    <div>
        <span id="time_left"></span>
    </div>
 
<script src="{{ p5 }}"></script>
</center>


{% endblock content %}

QRsite/QRer/templates/QRer/result.html
{% extends "base.html" %}

{% block title %}
こんにちは
{% endblock title %}

{% block content %}
<h1>とりあえずのコンテンツ</h1>

<img src="https://chart.apis.google.com/chart?cht=qr&chs=150x150&chl=123" alt="試し">
<img src="{{ QRl }}" alt="QRコード">
<p>成功です</p>
<p>入力された数字は {{ QRl }} です。</p>

<div>
    <p>残り時間　<span id="time_left" data-time-left="{{ time_left }}"></span></p>
</div>

<script src="/static/js/sample.js"></script>

{% endblock content %}

QRsite/QRer/templates/QRer/top.html
{% extends "base.html" %}
{% load static %} 

{% block title %}
こんにちは
{% endblock title %}

{% block content %}
<h2>こんにちは</h2>


<div class="row mt-4">
    <div class="col-md-6">
        <div class="card mb-3 bg-light">
            <div class="card-body">
                <h4 class="card-title">専用QRコード表示</h4>
                <p class="card-text">ログインしていると出席登録の専用QRコードを表示することができます。</p>
                <a href='{% url "QRer:index" %}' class="btn btn-outline-info">こちらから</a>
            </div>
        </div>
    </div>

    <div class="col-md-6">
        <div class="card mb-3 bg-light">
            <div class="card-body">
                <h4 class="card-title">ご意見・ご感想</h4>
                <p class="card-text">私たちが作成しているシステムやこのWebサイトなどについてのご意見・ご感想を送っていただけると幸いです。</p>
                <a href='{% url "QRer:contact" %}' class="btn btn-outline-info">こちらから</a>
            </div>
        </div>
    </div>

    {% if user.is_staff %}
    <div class="col-md-6">
        <div class="card mb-3 bg-light">
            <div class="card-body">
                <h4 class="card-title">専用QRコード生成</h4>
                <p class="card-text">【教員向け】学籍番号を入力して生徒の専用QRコードを生成することができます(通常用のみ)</p>
                <a href='{% url "QRer:maker" %}' class="btn btn-outline-info">こちらから</a>
            </div>
        </div>
    </div>

    <div class="col-md-6">
        <div class="card mb-3 bg-light">
            <div class="card-body">
                <h4 class="card-title">出席者データ確認</h4>
                <p class="card-text">【教員向け】Googleスプレッドシートの出席者データを参照できます</p>
                <a href='{% url "QRer:index" %}' class="btn btn-outline-info">こちらから</a>
            </div>
        </div>
    </div>

    {% endif %}
</div>


{% endblock content %}

QRsite/QRer/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0,shrink-to-fit=no">
    <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css' >
    <title>{% block title %}{% endblock %}</title>
    <style>body {padding-top: 80px;}</style>
</head>
<body>
    <nav class='navbar navbar-expand-md navbar-dark bg-info fixed-top'>
        <a class='navbar-brand' href='{% url "QRer:frontpage" %}'>QRコードで出席登録</a>
        <ul class='navbar-nav'>
            {% if user.is_authenticated %}
                <li class='nav-time'>
                    <span class='navbar-text'>{{ user }} - </span>
                </li>
                <li class='nav-item'>
                    <a href='{% url "QRer:logout" %}' class='logout nav-link'>ログアウト</a>
                </li>
            {% else %}
                <a href='{% url "QRer:login" %}' class='login nav-link'>ログインはこちら</a>
            {% endif %}
        </ul>
    </nav>
    <div class="container">
    {% block content %}
    {% endblock %}
    </div> 
</body>
</html>

QRsite/accounts/templates/accounts/signup.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0,shrink-to-fit=no">
    <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css' >
    <title>{% block title %}{% endblock %}</title>
    <style>body {padding-top: 80px;}</style>
</head>
<body>
    <nav class='navbar navbar-expand-md navbar-dark bg-info fixed-top'>
        <a class='navbar-brand' href='{% url "QRer:frontpage" %}'>QRコード表示サイト</a>
        <ul class='navbar-nav'>
            {% if user.is_authenticated %}
                <li class='nav-time'>
                    <span class='navbar-text'>{{ user }} - </span>
                </li>
                <li class='nav-item'>
                    <a href='{% url "QRer:logout" %}' class='logout nav-link'>ログアウト</a>
                </li>
            {% else %}
                <a href='{% url "QRer:login" %}' class='login nav-link'>ログインはこちら</a>
            {% endif %}
        </ul>
    </nav>
    <div class="container">
    {% block content %}
    {% endblock %}
    </div> 
</body>
</html>